package modele;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Anneebudgetaire generated by hbm2java
 */
@Entity
@Table(name="anneebudgetaire"
    ,catalog="finance_fssm"
)
public class Anneebudgetaire  implements java.io.Serializable {


     private Integer annee;
     private Integer montantRap;
     private Integer reliquatRap;

    public Anneebudgetaire() {
    }

    public Anneebudgetaire(Integer montantRap, Integer reliquatRap) {
       this.montantRap = montantRap;
       this.reliquatRap = reliquatRap;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="annee", unique=true, nullable=false)
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }

    
    @Column(name="montantRap", precision=8, scale=0)
    public Integer getMontantRap() {
        return this.montantRap;
    }
    
    public void setMontantRap(Integer montantRap) {
        this.montantRap = montantRap;
    }

    
    @Column(name="reliquatRap", precision=8, scale=0)
    public Integer getReliquatRap() {
        return this.reliquatRap;
    }
    
    public void setReliquatRap(Integer reliquatRap) {
        this.reliquatRap = reliquatRap;
    }




}


