package modele;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bordereauautorisation generated by hbm2java
 */
@Entity
@Table(name="bordereauautorisation"
    ,catalog="finance_fssm"
)
public class Bordereauautorisation  implements java.io.Serializable {


     private Integer idBordAut;
     private Integer anneeUniversitaire;

    public Bordereauautorisation() {
    }

    public Bordereauautorisation(Integer anneeUniversitaire) {
       this.anneeUniversitaire = anneeUniversitaire;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBordAut", unique=true, nullable=false)
    public Integer getIdBordAut() {
        return this.idBordAut;
    }
    
    public void setIdBordAut(Integer idBordAut) {
        this.idBordAut = idBordAut;
    }

    
    @Column(name="anneeUniversitaire")
    public Integer getAnneeUniversitaire() {
        return this.anneeUniversitaire;
    }
    
    public void setAnneeUniversitaire(Integer anneeUniversitaire) {
        this.anneeUniversitaire = anneeUniversitaire;
    }




}


