package modele;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Indemnetedeplacementinterne generated by hbm2java
 */
@Entity
@Table(name="indemnetedeplacementinterne"
    ,catalog="finance_fssm"
)
public class Indemnetedeplacementinterne  implements java.io.Serializable {


     private IndemnetedeplacementinterneId id;
     private Integer idPrixRepas;
     private int idDotation;
     private Integer montantDepInt;

    public Indemnetedeplacementinterne() {
    }

	
    public Indemnetedeplacementinterne(IndemnetedeplacementinterneId id, int idDotation) {
        this.id = id;
        this.idDotation = idDotation;
    }
    public Indemnetedeplacementinterne(IndemnetedeplacementinterneId id, Integer idPrixRepas, int idDotation, Integer montantDepInt) {
       this.id = id;
       this.idPrixRepas = idPrixRepas;
       this.idDotation = idDotation;
       this.montantDepInt = montantDepInt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDeplacement", column=@Column(name="idDeplacement", nullable=false) ), 
        @AttributeOverride(name="idIndDep", column=@Column(name="idIndDep", nullable=false) ) } )
    public IndemnetedeplacementinterneId getId() {
        return this.id;
    }
    
    public void setId(IndemnetedeplacementinterneId id) {
        this.id = id;
    }

    
    @Column(name="idPrixRepas")
    public Integer getIdPrixRepas() {
        return this.idPrixRepas;
    }
    
    public void setIdPrixRepas(Integer idPrixRepas) {
        this.idPrixRepas = idPrixRepas;
    }

    
    @Column(name="idDotation", nullable=false)
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }

    
    @Column(name="montantDepInt", precision=8, scale=0)
    public Integer getMontantDepInt() {
        return this.montantDepInt;
    }
    
    public void setMontantDepInt(Integer montantDepInt) {
        this.montantDepInt = montantDepInt;
    }




}


