package modele;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prixsejour generated by hbm2java
 */
@Entity
@Table(name="prixsejour"
    ,catalog="finance_fssm"
)
public class Prixsejour  implements java.io.Serializable {


     private Integer idPrixSej;
     private Integer grade;
     private Integer prix;

    public Prixsejour() {
    }

    public Prixsejour(Integer grade, Integer prix) {
       this.grade = grade;
       this.prix = prix;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPrixSej", unique=true, nullable=false)
    public Integer getIdPrixSej() {
        return this.idPrixSej;
    }
    
    public void setIdPrixSej(Integer idPrixSej) {
        this.idPrixSej = idPrixSej;
    }

    
    @Column(name="grade")
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    
    @Column(name="prix")
    public Integer getPrix() {
        return this.prix;
    }
    
    public void setPrix(Integer prix) {
        this.prix = prix;
    }




}


