package modele;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Secteurprincipal generated by hbm2java
 */
@Entity
@Table(name="secteurprincipal"
    ,catalog="finance_fssm"
)
public class Secteurprincipal  implements java.io.Serializable {


     private Integer idSecteurP;
     private String designation;

    public Secteurprincipal() {
    }

    public Secteurprincipal(String designation) {
       this.designation = designation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSecteurP", unique=true, nullable=false)
    public Integer getIdSecteurP() {
        return this.idSecteurP;
    }
    
    public void setIdSecteurP(Integer idSecteurP) {
        this.idSecteurP = idSecteurP;
    }

    
    @Column(name="designation", length=254)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


