package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Anneebudgetaire generated by hbm2java
 */
public class Anneebudgetaire  implements java.io.Serializable {


     private Integer annee;
     private Integer montantRap;
     private Integer reliquatRap;

    public Anneebudgetaire() {
    }

    public Anneebudgetaire(Integer montantRap, Integer reliquatRap) {
       this.montantRap = montantRap;
       this.reliquatRap = reliquatRap;
    }
   
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }
    public Integer getMontantRap() {
        return this.montantRap;
    }
    
    public void setMontantRap(Integer montantRap) {
        this.montantRap = montantRap;
    }
    public Integer getReliquatRap() {
        return this.reliquatRap;
    }
    
    public void setReliquatRap(Integer reliquatRap) {
        this.reliquatRap = reliquatRap;
    }




}


