package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name="article"
    ,catalog="finance_fssm"
)
public class Article  implements java.io.Serializable {


     private Integer idArticle;
     private String description;
     private Integer pu;

    public Article() {
    }

    public Article(String description, Integer pu) {
       this.description = description;
       this.pu = pu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArticle", unique=true, nullable=false)
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }

    
    @Column(name="description", length=254)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="pu", precision=8, scale=0)
    public Integer getPu() {
        return this.pu;
    }
    
    public void setPu(Integer pu) {
        this.pu = pu;
    }




}


