package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idArticle;
     private String description;
     private Integer pu;

    public Article() {
    }

    public Article(String description, Integer pu) {
       this.description = description;
       this.pu = pu;
    }
   
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getPu() {
        return this.pu;
    }
    
    public void setPu(Integer pu) {
        this.pu = pu;
    }




}


