package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boncommande generated by hbm2java
 */
@Entity
@Table(name="boncommande"
    ,catalog="finance_fssm"
)
public class Boncommande  implements java.io.Serializable {


     private Integer idBc;
     private int idFournisseur;
     private int idUser;
     private int idDotation;
     private Date dateCommande;
     private Integer tva;
     private Date dateReception;
     private String etat;
     private Integer montant;
     private String type;

    public Boncommande() {
    }

	
    public Boncommande(int idFournisseur, int idUser, int idDotation) {
        this.idFournisseur = idFournisseur;
        this.idUser = idUser;
        this.idDotation = idDotation;
    }
    public Boncommande(int idFournisseur, int idUser, int idDotation, Date dateCommande, Integer tva, Date dateReception, String etat, Integer montant, String type) {
       this.idFournisseur = idFournisseur;
       this.idUser = idUser;
       this.idDotation = idDotation;
       this.dateCommande = dateCommande;
       this.tva = tva;
       this.dateReception = dateReception;
       this.etat = etat;
       this.montant = montant;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBC", unique=true, nullable=false)
    public Integer getIdBc() {
        return this.idBc;
    }
    
    public void setIdBc(Integer idBc) {
        this.idBc = idBc;
    }

    
    @Column(name="idFournisseur", nullable=false)
    public int getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(int idFournisseur) {
        this.idFournisseur = idFournisseur;
    }

    
    @Column(name="idUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="idDotation", nullable=false)
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCommande", length=19)
    public Date getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(Date dateCommande) {
        this.dateCommande = dateCommande;
    }

    
    @Column(name="tva")
    public Integer getTva() {
        return this.tva;
    }
    
    public void setTva(Integer tva) {
        this.tva = tva;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateReception", length=19)
    public Date getDateReception() {
        return this.dateReception;
    }
    
    public void setDateReception(Date dateReception) {
        this.dateReception = dateReception;
    }

    
    @Column(name="etat", length=254)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="montant", precision=8, scale=0)
    public Integer getMontant() {
        return this.montant;
    }
    
    public void setMontant(Integer montant) {
        this.montant = montant;
    }

    
    @Column(name="type", length=254)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


