package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bordereaucomptable generated by hbm2java
 */
public class Bordereaucomptable  implements java.io.Serializable {


     private Integer idBordComp;
     private int annee;
     private Date dateExercice;
     private Integer totalIr;
     private Integer totalNet;

    public Bordereaucomptable() {
    }

	
    public Bordereaucomptable(int annee) {
        this.annee = annee;
    }
    public Bordereaucomptable(int annee, Date dateExercice, Integer totalIr, Integer totalNet) {
       this.annee = annee;
       this.dateExercice = dateExercice;
       this.totalIr = totalIr;
       this.totalNet = totalNet;
    }
   
    public Integer getIdBordComp() {
        return this.idBordComp;
    }
    
    public void setIdBordComp(Integer idBordComp) {
        this.idBordComp = idBordComp;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }
    public Date getDateExercice() {
        return this.dateExercice;
    }
    
    public void setDateExercice(Date dateExercice) {
        this.dateExercice = dateExercice;
    }
    public Integer getTotalIr() {
        return this.totalIr;
    }
    
    public void setTotalIr(Integer totalIr) {
        this.totalIr = totalIr;
    }
    public Integer getTotalNet() {
        return this.totalNet;
    }
    
    public void setTotalNet(Integer totalNet) {
        this.totalNet = totalNet;
    }




}


