package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bordereaucomptable generated by hbm2java
 */
@Entity
@Table(name="bordereaucomptable"
    ,catalog="bd_finance_fssm"
)
public class Bordereaucomptable  implements java.io.Serializable {


     private Integer idBordComp;
     private int annee;
     private Date dateExercice;
     private Integer totalIr;
     private Integer totalNet;

    public Bordereaucomptable() {
    }

	
    public Bordereaucomptable(int annee) {
        this.annee = annee;
    }
    public Bordereaucomptable(int annee, Date dateExercice, Integer totalIr, Integer totalNet) {
       this.annee = annee;
       this.dateExercice = dateExercice;
       this.totalIr = totalIr;
       this.totalNet = totalNet;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idBordComp", unique=true, nullable=false)
    public Integer getIdBordComp() {
        return this.idBordComp;
    }
    
    public void setIdBordComp(Integer idBordComp) {
        this.idBordComp = idBordComp;
    }

    
    @Column(name="annee", nullable=false)
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateExercice", length=19)
    public Date getDateExercice() {
        return this.dateExercice;
    }
    
    public void setDateExercice(Date dateExercice) {
        this.dateExercice = dateExercice;
    }

    
    @Column(name="totalIr", precision=8, scale=0)
    public Integer getTotalIr() {
        return this.totalIr;
    }
    
    public void setTotalIr(Integer totalIr) {
        this.totalIr = totalIr;
    }

    
    @Column(name="totalNet", precision=8, scale=0)
    public Integer getTotalNet() {
        return this.totalNet;
    }
    
    public void setTotalNet(Integer totalNet) {
        this.totalNet = totalNet;
    }




}


