package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Bordereauautorisation generated by hbm2java
 */
public class Bordereauautorisation  implements java.io.Serializable {


     private Integer idBordAut;
     private Integer anneeUniversitaire;

    public Bordereauautorisation() {
    }

    public Bordereauautorisation(Integer anneeUniversitaire) {
       this.anneeUniversitaire = anneeUniversitaire;
    }
   
    public Integer getIdBordAut() {
        return this.idBordAut;
    }
    
    public void setIdBordAut(Integer idBordAut) {
        this.idBordAut = idBordAut;
    }
    public Integer getAnneeUniversitaire() {
        return this.anneeUniversitaire;
    }
    
    public void setAnneeUniversitaire(Integer anneeUniversitaire) {
        this.anneeUniversitaire = anneeUniversitaire;
    }




}


