package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Budget generated by hbm2java
 */
@Entity
@Table(name="budget"
    ,catalog="finance_fssm"
)
public class Budget  implements java.io.Serializable {


     private BudgetId id;
     private Integer budgetAnnuel;
     private Integer reliquat;

    public Budget() {
    }

	
    public Budget(BudgetId id) {
        this.id = id;
    }
    public Budget(BudgetId id, Integer budgetAnnuel, Integer reliquat) {
       this.id = id;
       this.budgetAnnuel = budgetAnnuel;
       this.reliquat = reliquat;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCompte", column=@Column(name="idCompte", nullable=false) ), 
        @AttributeOverride(name="annee", column=@Column(name="annee", nullable=false) ) } )
    public BudgetId getId() {
        return this.id;
    }
    
    public void setId(BudgetId id) {
        this.id = id;
    }

    
    @Column(name="budgetAnnuel", precision=8, scale=0)
    public Integer getBudgetAnnuel() {
        return this.budgetAnnuel;
    }
    
    public void setBudgetAnnuel(Integer budgetAnnuel) {
        this.budgetAnnuel = budgetAnnuel;
    }

    
    @Column(name="reliquat", precision=8, scale=0)
    public Integer getReliquat() {
        return this.reliquat;
    }
    
    public void setReliquat(Integer reliquat) {
        this.reliquat = reliquat;
    }




}


