package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BudgetId generated by hbm2java
 */
@Embeddable
public class BudgetId  implements java.io.Serializable {


     private int idCompte;
     private int annee;

    public BudgetId() {
    }

    public BudgetId(int idCompte, int annee) {
       this.idCompte = idCompte;
       this.annee = annee;
    }
   


    @Column(name="idCompte", nullable=false)
    public int getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }


    @Column(name="annee", nullable=false)
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BudgetId) ) return false;
		 BudgetId castOther = ( BudgetId ) other; 
         
		 return (this.getIdCompte()==castOther.getIdCompte())
 && (this.getAnnee()==castOther.getAnnee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCompte();
         result = 37 * result + this.getAnnee();
         return result;
   }   


}


