package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Budget generated by hbm2java
 */
public class Budget  implements java.io.Serializable {


     private BudgetId id;
     private Integer budgetAnnuel;
     private Integer reliquat;

    public Budget() {
    }

	
    public Budget(BudgetId id) {
        this.id = id;
    }
    public Budget(BudgetId id, Integer budgetAnnuel, Integer reliquat) {
       this.id = id;
       this.budgetAnnuel = budgetAnnuel;
       this.reliquat = reliquat;
    }
   
    public BudgetId getId() {
        return this.id;
    }
    
    public void setId(BudgetId id) {
        this.id = id;
    }
    public Integer getBudgetAnnuel() {
        return this.budgetAnnuel;
    }
    
    public void setBudgetAnnuel(Integer budgetAnnuel) {
        this.budgetAnnuel = budgetAnnuel;
    }
    public Integer getReliquat() {
        return this.reliquat;
    }
    
    public void setReliquat(Integer reliquat) {
        this.reliquat = reliquat;
    }




}


