package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comptebc generated by hbm2java
 */
@Entity
@Table(name="comptebc"
    ,catalog="bd_finance_fssm"
)
public class Comptebc  implements java.io.Serializable {


     private Integer idCptBc;
     private String cinPpr;
     private String intitule;
     private String bc;
     private String rib;

    public Comptebc() {
    }

	
    public Comptebc(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public Comptebc(String cinPpr, String intitule, String bc, String rib) {
       this.cinPpr = cinPpr;
       this.intitule = intitule;
       this.bc = bc;
       this.rib = rib;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCptBc", unique=true, nullable=false)
    public Integer getIdCptBc() {
        return this.idCptBc;
    }
    
    public void setIdCptBc(Integer idCptBc) {
        this.idCptBc = idCptBc;
    }

    
    @Column(name="cinPpr", nullable=false, length=254)
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }

    
    @Column(name="intitule", length=254)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    
    @Column(name="bc", length=254)
    public String getBc() {
        return this.bc;
    }
    
    public void setBc(String bc) {
        this.bc = bc;
    }

    
    @Column(name="rib", length=254)
    public String getRib() {
        return this.rib;
    }
    
    public void setRib(String rib) {
        this.rib = rib;
    }




}


