package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Comptebc generated by hbm2java
 */
public class Comptebc  implements java.io.Serializable {


     private Integer idCptBc;
     private String cinPpr;
     private String intitule;
     private String bc;
     private String rib;

    public Comptebc() {
    }

	
    public Comptebc(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public Comptebc(String cinPpr, String intitule, String bc, String rib) {
       this.cinPpr = cinPpr;
       this.intitule = intitule;
       this.bc = bc;
       this.rib = rib;
    }
   
    public Integer getIdCptBc() {
        return this.idCptBc;
    }
    
    public void setIdCptBc(Integer idCptBc) {
        this.idCptBc = idCptBc;
    }
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    public String getBc() {
        return this.bc;
    }
    
    public void setBc(String bc) {
        this.bc = bc;
    }
    public String getRib() {
        return this.rib;
    }
    
    public void setRib(String rib) {
        this.rib = rib;
    }




}


