package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name="compte"
    ,catalog="bd_finance_fssm"
)
public class Compte  implements java.io.Serializable {


     private Integer idCompte;
     private String intitule;
     private Integer rap;

    public Compte() {
    }

    public Compte(String intitule, Integer rap) {
       this.intitule = intitule;
       this.rap = rap;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCompte", unique=true, nullable=false)
    public Integer getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(Integer idCompte) {
        this.idCompte = idCompte;
    }

    
    @Column(name="intitule", length=254)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    
    @Column(name="rap", precision=8, scale=0)
    public Integer getRap() {
        return this.rap;
    }
    
    public void setRap(Integer rap) {
        this.rap = rap;
    }




}


