package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private Integer idCompte;
     private String intitule;
     private Integer rap;

    public Compte() {
    }

    public Compte(String intitule, Integer rap) {
       this.intitule = intitule;
       this.rap = rap;
    }
   
    public Integer getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(Integer idCompte) {
        this.idCompte = idCompte;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    public Integer getRap() {
        return this.rap;
    }
    
    public void setRap(Integer rap) {
        this.rap = rap;
    }




}


