package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name="departement"
    ,catalog="bd_finance_fssm"
)
public class Departement  implements java.io.Serializable {


     private Integer idDep;
     private Integer idUser;
     private String nomDep;

    public Departement() {
    }

    public Departement(Integer idUser, String nomDep) {
       this.idUser = idUser;
       this.nomDep = nomDep;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDep", unique=true, nullable=false)
    public Integer getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(Integer idDep) {
        this.idDep = idDep;
    }

    
    @Column(name="idUser")
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="nomDep", length=254)
    public String getNomDep() {
        return this.nomDep;
    }
    
    public void setNomDep(String nomDep) {
        this.nomDep = nomDep;
    }




}


