package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Departement generated by hbm2java
 */
public class Departement  implements java.io.Serializable {


     private Integer idDep;
     private Integer idUser;
     private String nomDep;

    public Departement() {
    }

    public Departement(Integer idUser, String nomDep) {
       this.idUser = idUser;
       this.nomDep = nomDep;
    }
   
    public Integer getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(Integer idDep) {
        this.idDep = idDep;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNomDep() {
        return this.nomDep;
    }
    
    public void setNomDep(String nomDep) {
        this.nomDep = nomDep;
    }




}


