package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Deplacement generated by hbm2java
 */
public class Deplacement  implements java.io.Serializable {


     private Integer idDeplacement;
     private String cinPpr;
     private int idUser;
     private Integer idPays;
     private Integer nbrJours;
     private Date dateDepart;
     private Date dateArrive;
     private Integer annee;
     private String motifDeplacement;
     private Date dateCreation;
     private Integer statutMnt;
     private Integer indice;
     private Integer echelle;
     private String grade;

    public Deplacement() {
    }

	
    public Deplacement(String cinPpr, int idUser) {
        this.cinPpr = cinPpr;
        this.idUser = idUser;
    }
    public Deplacement(String cinPpr, int idUser, Integer idPays, Integer nbrJours, Date dateDepart, Date dateArrive, Integer annee, String motifDeplacement, Date dateCreation, Integer statutMnt, Integer indice, Integer echelle, String grade) {
       this.cinPpr = cinPpr;
       this.idUser = idUser;
       this.idPays = idPays;
       this.nbrJours = nbrJours;
       this.dateDepart = dateDepart;
       this.dateArrive = dateArrive;
       this.annee = annee;
       this.motifDeplacement = motifDeplacement;
       this.dateCreation = dateCreation;
       this.statutMnt = statutMnt;
       this.indice = indice;
       this.echelle = echelle;
       this.grade = grade;
    }
   
    public Integer getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(Integer idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public Integer getIdPays() {
        return this.idPays;
    }
    
    public void setIdPays(Integer idPays) {
        this.idPays = idPays;
    }
    public Integer getNbrJours() {
        return this.nbrJours;
    }
    
    public void setNbrJours(Integer nbrJours) {
        this.nbrJours = nbrJours;
    }
    public Date getDateDepart() {
        return this.dateDepart;
    }
    
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }
    public Date getDateArrive() {
        return this.dateArrive;
    }
    
    public void setDateArrive(Date dateArrive) {
        this.dateArrive = dateArrive;
    }
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }
    public String getMotifDeplacement() {
        return this.motifDeplacement;
    }
    
    public void setMotifDeplacement(String motifDeplacement) {
        this.motifDeplacement = motifDeplacement;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public Integer getStatutMnt() {
        return this.statutMnt;
    }
    
    public void setStatutMnt(Integer statutMnt) {
        this.statutMnt = statutMnt;
    }
    public Integer getIndice() {
        return this.indice;
    }
    
    public void setIndice(Integer indice) {
        this.indice = indice;
    }
    public Integer getEchelle() {
        return this.echelle;
    }
    
    public void setEchelle(Integer echelle) {
        this.echelle = echelle;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }




}


