package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Detail generated by hbm2java
 */
public class Detail  implements java.io.Serializable {


     private Integer idDetail;
     private Integer salaireAnnuelleBrut;
     private Integer allocationFamiliale;
     private Integer brutAdditionner;
     private Integer amo;
     private Integer retenuCmr;
     private Integer mutuelleMutialiste;
     private Integer mutuelleCaisse;
     private Integer rachatCmr;
     private Integer sommeDeduire;
     private Integer nbrEnfant;
     private Boolean conjoint;
     private Integer chargeFamiliale;
     private Integer irSource;
     private Integer irComplement;
     private Integer net;
     private Integer ir;
     private String echelle;
     private String echelon;

    public Detail() {
    }

    public Detail(Integer salaireAnnuelleBrut, Integer allocationFamiliale, Integer brutAdditionner, Integer amo, Integer retenuCmr, Integer mutuelleMutialiste, Integer mutuelleCaisse, Integer rachatCmr, Integer sommeDeduire, Integer nbrEnfant, Boolean conjoint, Integer chargeFamiliale, Integer irSource, Integer irComplement, Integer net, Integer ir, String echelle, String echelon) {
       this.salaireAnnuelleBrut = salaireAnnuelleBrut;
       this.allocationFamiliale = allocationFamiliale;
       this.brutAdditionner = brutAdditionner;
       this.amo = amo;
       this.retenuCmr = retenuCmr;
       this.mutuelleMutialiste = mutuelleMutialiste;
       this.mutuelleCaisse = mutuelleCaisse;
       this.rachatCmr = rachatCmr;
       this.sommeDeduire = sommeDeduire;
       this.nbrEnfant = nbrEnfant;
       this.conjoint = conjoint;
       this.chargeFamiliale = chargeFamiliale;
       this.irSource = irSource;
       this.irComplement = irComplement;
       this.net = net;
       this.ir = ir;
       this.echelle = echelle;
       this.echelon = echelon;
    }
   
    public Integer getIdDetail() {
        return this.idDetail;
    }
    
    public void setIdDetail(Integer idDetail) {
        this.idDetail = idDetail;
    }
    public Integer getSalaireAnnuelleBrut() {
        return this.salaireAnnuelleBrut;
    }
    
    public void setSalaireAnnuelleBrut(Integer salaireAnnuelleBrut) {
        this.salaireAnnuelleBrut = salaireAnnuelleBrut;
    }
    public Integer getAllocationFamiliale() {
        return this.allocationFamiliale;
    }
    
    public void setAllocationFamiliale(Integer allocationFamiliale) {
        this.allocationFamiliale = allocationFamiliale;
    }
    public Integer getBrutAdditionner() {
        return this.brutAdditionner;
    }
    
    public void setBrutAdditionner(Integer brutAdditionner) {
        this.brutAdditionner = brutAdditionner;
    }
    public Integer getAmo() {
        return this.amo;
    }
    
    public void setAmo(Integer amo) {
        this.amo = amo;
    }
    public Integer getRetenuCmr() {
        return this.retenuCmr;
    }
    
    public void setRetenuCmr(Integer retenuCmr) {
        this.retenuCmr = retenuCmr;
    }
    public Integer getMutuelleMutialiste() {
        return this.mutuelleMutialiste;
    }
    
    public void setMutuelleMutialiste(Integer mutuelleMutialiste) {
        this.mutuelleMutialiste = mutuelleMutialiste;
    }
    public Integer getMutuelleCaisse() {
        return this.mutuelleCaisse;
    }
    
    public void setMutuelleCaisse(Integer mutuelleCaisse) {
        this.mutuelleCaisse = mutuelleCaisse;
    }
    public Integer getRachatCmr() {
        return this.rachatCmr;
    }
    
    public void setRachatCmr(Integer rachatCmr) {
        this.rachatCmr = rachatCmr;
    }
    public Integer getSommeDeduire() {
        return this.sommeDeduire;
    }
    
    public void setSommeDeduire(Integer sommeDeduire) {
        this.sommeDeduire = sommeDeduire;
    }
    public Integer getNbrEnfant() {
        return this.nbrEnfant;
    }
    
    public void setNbrEnfant(Integer nbrEnfant) {
        this.nbrEnfant = nbrEnfant;
    }
    public Boolean getConjoint() {
        return this.conjoint;
    }
    
    public void setConjoint(Boolean conjoint) {
        this.conjoint = conjoint;
    }
    public Integer getChargeFamiliale() {
        return this.chargeFamiliale;
    }
    
    public void setChargeFamiliale(Integer chargeFamiliale) {
        this.chargeFamiliale = chargeFamiliale;
    }
    public Integer getIrSource() {
        return this.irSource;
    }
    
    public void setIrSource(Integer irSource) {
        this.irSource = irSource;
    }
    public Integer getIrComplement() {
        return this.irComplement;
    }
    
    public void setIrComplement(Integer irComplement) {
        this.irComplement = irComplement;
    }
    public Integer getNet() {
        return this.net;
    }
    
    public void setNet(Integer net) {
        this.net = net;
    }
    public Integer getIr() {
        return this.ir;
    }
    
    public void setIr(Integer ir) {
        this.ir = ir;
    }
    public String getEchelle() {
        return this.echelle;
    }
    
    public void setEchelle(String echelle) {
        this.echelle = echelle;
    }
    public String getEchelon() {
        return this.echelon;
    }
    
    public void setEchelon(String echelon) {
        this.echelon = echelon;
    }




}


