package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dossierrejete generated by hbm2java
 */
@Entity
@Table(name="dossierrejete"
    ,catalog="bd_finance_fssm"
)
public class Dossierrejete  implements java.io.Serializable {


     private Integer idDossierRejete;
     private int idDossier;
     private int dosIdDossier;
     private String motifRejet;

    public Dossierrejete() {
    }

	
    public Dossierrejete(int idDossier, int dosIdDossier) {
        this.idDossier = idDossier;
        this.dosIdDossier = dosIdDossier;
    }
    public Dossierrejete(int idDossier, int dosIdDossier, String motifRejet) {
       this.idDossier = idDossier;
       this.dosIdDossier = dosIdDossier;
       this.motifRejet = motifRejet;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDossierRejete", unique=true, nullable=false)
    public Integer getIdDossierRejete() {
        return this.idDossierRejete;
    }
    
    public void setIdDossierRejete(Integer idDossierRejete) {
        this.idDossierRejete = idDossierRejete;
    }

    
    @Column(name="idDossier", nullable=false)
    public int getIdDossier() {
        return this.idDossier;
    }
    
    public void setIdDossier(int idDossier) {
        this.idDossier = idDossier;
    }

    
    @Column(name="Dos_idDossier", nullable=false)
    public int getDosIdDossier() {
        return this.dosIdDossier;
    }
    
    public void setDosIdDossier(int dosIdDossier) {
        this.dosIdDossier = dosIdDossier;
    }

    
    @Column(name="motifRejet", length=254)
    public String getMotifRejet() {
        return this.motifRejet;
    }
    
    public void setMotifRejet(String motifRejet) {
        this.motifRejet = motifRejet;
    }




}


