package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Dossierrejete generated by hbm2java
 */
public class Dossierrejete  implements java.io.Serializable {


     private Integer idDossierRejete;
     private int idDossier;
     private int dosIdDossier;
     private String motifRejet;

    public Dossierrejete() {
    }

	
    public Dossierrejete(int idDossier, int dosIdDossier) {
        this.idDossier = idDossier;
        this.dosIdDossier = dosIdDossier;
    }
    public Dossierrejete(int idDossier, int dosIdDossier, String motifRejet) {
       this.idDossier = idDossier;
       this.dosIdDossier = dosIdDossier;
       this.motifRejet = motifRejet;
    }
   
    public Integer getIdDossierRejete() {
        return this.idDossierRejete;
    }
    
    public void setIdDossierRejete(Integer idDossierRejete) {
        this.idDossierRejete = idDossierRejete;
    }
    public int getIdDossier() {
        return this.idDossier;
    }
    
    public void setIdDossier(int idDossier) {
        this.idDossier = idDossier;
    }
    public int getDosIdDossier() {
        return this.dosIdDossier;
    }
    
    public void setDosIdDossier(int dosIdDossier) {
        this.dosIdDossier = dosIdDossier;
    }
    public String getMotifRejet() {
        return this.motifRejet;
    }
    
    public void setMotifRejet(String motifRejet) {
        this.motifRejet = motifRejet;
    }




}


