package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dossierprovisoir generated by hbm2java
 */
@Entity
@Table(name="dossierprovisoir"
    ,catalog="bd_finance_fssm"
)
public class Dossierprovisoir  implements java.io.Serializable {


     private Integer idDossierProv;
     private Integer idRelever;
     private Integer idGrade;
     private String nomComplet;
     private String dernierDiplome;
     private Integer nbrHeures;
     private String module;
     private Boolean etat;
     private Date dateDebut;
     private Date dateFin;

    public Dossierprovisoir() {
    }

    public Dossierprovisoir(Integer idRelever, Integer idGrade, String nomComplet, String dernierDiplome, Integer nbrHeures, String module, Boolean etat, Date dateDebut, Date dateFin) {
       this.idRelever = idRelever;
       this.idGrade = idGrade;
       this.nomComplet = nomComplet;
       this.dernierDiplome = dernierDiplome;
       this.nbrHeures = nbrHeures;
       this.module = module;
       this.etat = etat;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDossierProv", unique=true, nullable=false)
    public Integer getIdDossierProv() {
        return this.idDossierProv;
    }
    
    public void setIdDossierProv(Integer idDossierProv) {
        this.idDossierProv = idDossierProv;
    }

    
    @Column(name="idRelever")
    public Integer getIdRelever() {
        return this.idRelever;
    }
    
    public void setIdRelever(Integer idRelever) {
        this.idRelever = idRelever;
    }

    
    @Column(name="idGrade")
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }

    
    @Column(name="nomComplet", length=254)
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }

    
    @Column(name="dernierDiplome", length=254)
    public String getDernierDiplome() {
        return this.dernierDiplome;
    }
    
    public void setDernierDiplome(String dernierDiplome) {
        this.dernierDiplome = dernierDiplome;
    }

    
    @Column(name="nbrHeures")
    public Integer getNbrHeures() {
        return this.nbrHeures;
    }
    
    public void setNbrHeures(Integer nbrHeures) {
        this.nbrHeures = nbrHeures;
    }

    
    @Column(name="module", length=254)
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }

    
    @Column(name="etat")
    public Boolean getEtat() {
        return this.etat;
    }
    
    public void setEtat(Boolean etat) {
        this.etat = etat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateDebut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateFin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


