package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dossierprovisoir generated by hbm2java
 */
public class Dossierprovisoir  implements java.io.Serializable {


     private Integer idDossierProv;
     private Integer idRelever;
     private Integer idGrade;
     private String nomComplet;
     private String dernierDiplome;
     private Integer nbrHeures;
     private String module;
     private Boolean etat;
     private Date dateDebut;
     private Date dateFin;

    public Dossierprovisoir() {
    }

    public Dossierprovisoir(Integer idRelever, Integer idGrade, String nomComplet, String dernierDiplome, Integer nbrHeures, String module, Boolean etat, Date dateDebut, Date dateFin) {
       this.idRelever = idRelever;
       this.idGrade = idGrade;
       this.nomComplet = nomComplet;
       this.dernierDiplome = dernierDiplome;
       this.nbrHeures = nbrHeures;
       this.module = module;
       this.etat = etat;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
    }
   
    public Integer getIdDossierProv() {
        return this.idDossierProv;
    }
    
    public void setIdDossierProv(Integer idDossierProv) {
        this.idDossierProv = idDossierProv;
    }
    public Integer getIdRelever() {
        return this.idRelever;
    }
    
    public void setIdRelever(Integer idRelever) {
        this.idRelever = idRelever;
    }
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }
    public String getDernierDiplome() {
        return this.dernierDiplome;
    }
    
    public void setDernierDiplome(String dernierDiplome) {
        this.dernierDiplome = dernierDiplome;
    }
    public Integer getNbrHeures() {
        return this.nbrHeures;
    }
    
    public void setNbrHeures(Integer nbrHeures) {
        this.nbrHeures = nbrHeures;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public Boolean getEtat() {
        return this.etat;
    }
    
    public void setEtat(Boolean etat) {
        this.etat = etat;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


