package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dossiervacataire generated by hbm2java
 */
public class Dossiervacataire  implements java.io.Serializable {


     private Integer idDossier;
     private String cinPpr;
     private Integer idBordAut;
     private int idDossierProv;
     private Integer idBordComp;
     private int idDotation;
     private Integer idGrade;
     private Integer nbrHeures;
     private String mois;
     private String semestre;
     private Date dateCreance;
     private Integer net;
     private Integer ir;
     private String statutDossier;

    public Dossiervacataire() {
    }

	
    public Dossiervacataire(String cinPpr, int idDossierProv, int idDotation) {
        this.cinPpr = cinPpr;
        this.idDossierProv = idDossierProv;
        this.idDotation = idDotation;
    }
    public Dossiervacataire(String cinPpr, Integer idBordAut, int idDossierProv, Integer idBordComp, int idDotation, Integer idGrade, Integer nbrHeures, String mois, String semestre, Date dateCreance, Integer net, Integer ir, String statutDossier) {
       this.cinPpr = cinPpr;
       this.idBordAut = idBordAut;
       this.idDossierProv = idDossierProv;
       this.idBordComp = idBordComp;
       this.idDotation = idDotation;
       this.idGrade = idGrade;
       this.nbrHeures = nbrHeures;
       this.mois = mois;
       this.semestre = semestre;
       this.dateCreance = dateCreance;
       this.net = net;
       this.ir = ir;
       this.statutDossier = statutDossier;
    }
   
    public Integer getIdDossier() {
        return this.idDossier;
    }
    
    public void setIdDossier(Integer idDossier) {
        this.idDossier = idDossier;
    }
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public Integer getIdBordAut() {
        return this.idBordAut;
    }
    
    public void setIdBordAut(Integer idBordAut) {
        this.idBordAut = idBordAut;
    }
    public int getIdDossierProv() {
        return this.idDossierProv;
    }
    
    public void setIdDossierProv(int idDossierProv) {
        this.idDossierProv = idDossierProv;
    }
    public Integer getIdBordComp() {
        return this.idBordComp;
    }
    
    public void setIdBordComp(Integer idBordComp) {
        this.idBordComp = idBordComp;
    }
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }
    public Integer getNbrHeures() {
        return this.nbrHeures;
    }
    
    public void setNbrHeures(Integer nbrHeures) {
        this.nbrHeures = nbrHeures;
    }
    public String getMois() {
        return this.mois;
    }
    
    public void setMois(String mois) {
        this.mois = mois;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public Date getDateCreance() {
        return this.dateCreance;
    }
    
    public void setDateCreance(Date dateCreance) {
        this.dateCreance = dateCreance;
    }
    public Integer getNet() {
        return this.net;
    }
    
    public void setNet(Integer net) {
        this.net = net;
    }
    public Integer getIr() {
        return this.ir;
    }
    
    public void setIr(Integer ir) {
        this.ir = ir;
    }
    public String getStatutDossier() {
        return this.statutDossier;
    }
    
    public void setStatutDossier(String statutDossier) {
        this.statutDossier = statutDossier;
    }




}


