package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dotationsecteur generated by hbm2java
 */
@Entity
@Table(name="dotationsecteur"
    ,catalog="finance_fssm"
)
public class Dotationsecteur  implements java.io.Serializable {


     private Integer idDotation;
     private int idCompte;
     private int idSecteur;
     private Integer montantInitial;
     private Integer reliquat;

    public Dotationsecteur() {
    }

	
    public Dotationsecteur(int idCompte, int idSecteur) {
        this.idCompte = idCompte;
        this.idSecteur = idSecteur;
    }
    public Dotationsecteur(int idCompte, int idSecteur, Integer montantInitial, Integer reliquat) {
       this.idCompte = idCompte;
       this.idSecteur = idSecteur;
       this.montantInitial = montantInitial;
       this.reliquat = reliquat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDotation", unique=true, nullable=false)
    public Integer getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(Integer idDotation) {
        this.idDotation = idDotation;
    }

    
    @Column(name="idCompte", nullable=false)
    public int getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }

    
    @Column(name="idSecteur", nullable=false)
    public int getIdSecteur() {
        return this.idSecteur;
    }
    
    public void setIdSecteur(int idSecteur) {
        this.idSecteur = idSecteur;
    }

    
    @Column(name="montantInitial", precision=8, scale=0)
    public Integer getMontantInitial() {
        return this.montantInitial;
    }
    
    public void setMontantInitial(Integer montantInitial) {
        this.montantInitial = montantInitial;
    }

    
    @Column(name="reliquat", precision=8, scale=0)
    public Integer getReliquat() {
        return this.reliquat;
    }
    
    public void setReliquat(Integer reliquat) {
        this.reliquat = reliquat;
    }




}


