package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Dotationsecteur generated by hbm2java
 */
public class Dotationsecteur  implements java.io.Serializable {


     private Integer idDotation;
     private int idCompte;
     private int idSecteur;
     private Integer montantInitial;
     private Integer reliquat;

    public Dotationsecteur() {
    }

	
    public Dotationsecteur(int idCompte, int idSecteur) {
        this.idCompte = idCompte;
        this.idSecteur = idSecteur;
    }
    public Dotationsecteur(int idCompte, int idSecteur, Integer montantInitial, Integer reliquat) {
       this.idCompte = idCompte;
       this.idSecteur = idSecteur;
       this.montantInitial = montantInitial;
       this.reliquat = reliquat;
    }
   
    public Integer getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(Integer idDotation) {
        this.idDotation = idDotation;
    }
    public int getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }
    public int getIdSecteur() {
        return this.idSecteur;
    }
    
    public void setIdSecteur(int idSecteur) {
        this.idSecteur = idSecteur;
    }
    public Integer getMontantInitial() {
        return this.montantInitial;
    }
    
    public void setMontantInitial(Integer montantInitial) {
        this.montantInitial = montantInitial;
    }
    public Integer getReliquat() {
        return this.reliquat;
    }
    
    public void setReliquat(Integer reliquat) {
        this.reliquat = reliquat;
    }




}


