package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etatdossier generated by hbm2java
 */
@Entity
@Table(name="etatdossier"
    ,catalog="bd_finance_fssm"
)
public class Etatdossier  implements java.io.Serializable {


     private Integer idEtat;
     private int idDeplacement;
     private Integer etat;
     private String motif;
     private String rmq;
     private String observation;
     private Date dateEtat;

    public Etatdossier() {
    }

	
    public Etatdossier(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public Etatdossier(int idDeplacement, Integer etat, String motif, String rmq, String observation, Date dateEtat) {
       this.idDeplacement = idDeplacement;
       this.etat = etat;
       this.motif = motif;
       this.rmq = rmq;
       this.observation = observation;
       this.dateEtat = dateEtat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEtat", unique=true, nullable=false)
    public Integer getIdEtat() {
        return this.idEtat;
    }
    
    public void setIdEtat(Integer idEtat) {
        this.idEtat = idEtat;
    }

    
    @Column(name="idDeplacement", nullable=false)
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="motif", length=254)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

    
    @Column(name="rmq", length=254)
    public String getRmq() {
        return this.rmq;
    }
    
    public void setRmq(String rmq) {
        this.rmq = rmq;
    }

    
    @Column(name="observation", length=254)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateEtat", length=19)
    public Date getDateEtat() {
        return this.dateEtat;
    }
    
    public void setDateEtat(Date dateEtat) {
        this.dateEtat = dateEtat;
    }




}


