package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Filiere generated by hbm2java
 */
public class Filiere  implements java.io.Serializable {


     private Integer idFiliere;
     private int idDep;
     private int idType;
     private int idUser;
     private String intitule;

    public Filiere() {
    }

	
    public Filiere(int idDep, int idType, int idUser) {
        this.idDep = idDep;
        this.idType = idType;
        this.idUser = idUser;
    }
    public Filiere(int idDep, int idType, int idUser, String intitule) {
       this.idDep = idDep;
       this.idType = idType;
       this.idUser = idUser;
       this.intitule = intitule;
    }
   
    public Integer getIdFiliere() {
        return this.idFiliere;
    }
    
    public void setIdFiliere(Integer idFiliere) {
        this.idFiliere = idFiliere;
    }
    public int getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(int idDep) {
        this.idDep = idDep;
    }
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }




}


