package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur  implements java.io.Serializable {


     private Integer idFournisseur;
     private String nom;
     private String adresse;
     private String tel;
     private String email;

    public Fournisseur() {
    }

    public Fournisseur(String nom, String adresse, String tel, String email) {
       this.nom = nom;
       this.adresse = adresse;
       this.tel = tel;
       this.email = email;
    }
   
    public Integer getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(Integer idFournisseur) {
        this.idFournisseur = idFournisseur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


