package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name="fournisseur"
    ,catalog="bd_finance_fssm"
)
public class Fournisseur  implements java.io.Serializable {


     private Integer idFournisseur;
     private String nom;
     private String adresse;
     private String tel;
     private String email;

    public Fournisseur() {
    }

    public Fournisseur(String nom, String adresse, String tel, String email) {
       this.nom = nom;
       this.adresse = adresse;
       this.tel = tel;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFournisseur", unique=true, nullable=false)
    public Integer getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(Integer idFournisseur) {
        this.idFournisseur = idFournisseur;
    }

    
    @Column(name="nom", length=254)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="adresse", length=254)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel", length=254)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="email", length=254)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


