package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Graddiplome generated by hbm2java
 */
@Entity
@Table(name="graddiplome"
    ,catalog="finance_fssm"
)
public class Graddiplome  implements java.io.Serializable {


     private Integer idGrade;
     private String intituleGrade;
     private Integer taux;

    public Graddiplome() {
    }

    public Graddiplome(String intituleGrade, Integer taux) {
       this.intituleGrade = intituleGrade;
       this.taux = taux;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGrade", unique=true, nullable=false)
    public Integer getIdGrade() {
        return this.idGrade;
    }
    
    public void setIdGrade(Integer idGrade) {
        this.idGrade = idGrade;
    }

    
    @Column(name="intituleGrade", length=254)
    public String getIntituleGrade() {
        return this.intituleGrade;
    }
    
    public void setIntituleGrade(String intituleGrade) {
        this.intituleGrade = intituleGrade;
    }

    
    @Column(name="taux")
    public Integer getTaux() {
        return this.taux;
    }
    
    public void setTaux(Integer taux) {
        this.taux = taux;
    }




}


