package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Indemnetedeplacementetranger generated by hbm2java
 */
public class Indemnetedeplacementetranger  implements java.io.Serializable {


     private IndemnetedeplacementetrangerId id;
     private Integer idPrixSej;
     private int idDotation;
     private Integer mntDepEx;

    public Indemnetedeplacementetranger() {
    }

	
    public Indemnetedeplacementetranger(IndemnetedeplacementetrangerId id, int idDotation) {
        this.id = id;
        this.idDotation = idDotation;
    }
    public Indemnetedeplacementetranger(IndemnetedeplacementetrangerId id, Integer idPrixSej, int idDotation, Integer mntDepEx) {
       this.id = id;
       this.idPrixSej = idPrixSej;
       this.idDotation = idDotation;
       this.mntDepEx = mntDepEx;
    }
   
    public IndemnetedeplacementetrangerId getId() {
        return this.id;
    }
    
    public void setId(IndemnetedeplacementetrangerId id) {
        this.id = id;
    }
    public Integer getIdPrixSej() {
        return this.idPrixSej;
    }
    
    public void setIdPrixSej(Integer idPrixSej) {
        this.idPrixSej = idPrixSej;
    }
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }
    public Integer getMntDepEx() {
        return this.mntDepEx;
    }
    
    public void setMntDepEx(Integer mntDepEx) {
        this.mntDepEx = mntDepEx;
    }




}


