package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndemnetedeplacementetrangerId generated by hbm2java
 */
@Embeddable
public class IndemnetedeplacementetrangerId  implements java.io.Serializable {


     private int idDeplacement;
     private int idDepEx;

    public IndemnetedeplacementetrangerId() {
    }

    public IndemnetedeplacementetrangerId(int idDeplacement, int idDepEx) {
       this.idDeplacement = idDeplacement;
       this.idDepEx = idDepEx;
    }
   


    @Column(name="idDeplacement", nullable=false)
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }


    @Column(name="idDepEx", nullable=false)
    public int getIdDepEx() {
        return this.idDepEx;
    }
    
    public void setIdDepEx(int idDepEx) {
        this.idDepEx = idDepEx;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndemnetedeplacementetrangerId) ) return false;
		 IndemnetedeplacementetrangerId castOther = ( IndemnetedeplacementetrangerId ) other; 
         
		 return (this.getIdDeplacement()==castOther.getIdDeplacement())
 && (this.getIdDepEx()==castOther.getIdDepEx());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDeplacement();
         result = 37 * result + this.getIdDepEx();
         return result;
   }   


}


