package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Indemnetedeplacementinterne generated by hbm2java
 */
public class Indemnetedeplacementinterne  implements java.io.Serializable {


     private IndemnetedeplacementinterneId id;
     private Integer idPrixRepas;
     private int idDotation;
     private Integer montantDepInt;

    public Indemnetedeplacementinterne() {
    }

	
    public Indemnetedeplacementinterne(IndemnetedeplacementinterneId id, int idDotation) {
        this.id = id;
        this.idDotation = idDotation;
    }
    public Indemnetedeplacementinterne(IndemnetedeplacementinterneId id, Integer idPrixRepas, int idDotation, Integer montantDepInt) {
       this.id = id;
       this.idPrixRepas = idPrixRepas;
       this.idDotation = idDotation;
       this.montantDepInt = montantDepInt;
    }
   
    public IndemnetedeplacementinterneId getId() {
        return this.id;
    }
    
    public void setId(IndemnetedeplacementinterneId id) {
        this.id = id;
    }
    public Integer getIdPrixRepas() {
        return this.idPrixRepas;
    }
    
    public void setIdPrixRepas(Integer idPrixRepas) {
        this.idPrixRepas = idPrixRepas;
    }
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }
    public Integer getMontantDepInt() {
        return this.montantDepInt;
    }
    
    public void setMontantDepInt(Integer montantDepInt) {
        this.montantDepInt = montantDepInt;
    }




}


