package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Indemntekm generated by hbm2java
 */
@Entity
@Table(name="indemntekm"
    ,catalog="bd_finance_fssm"
)
public class Indemntekm  implements java.io.Serializable {


     private IndemntekmId id;
     private int idDotation;
     private Integer montantDepInt;
     private Integer kmRoute;
     private Integer kmPiste;
     private Integer mntKm;

    public Indemntekm() {
    }

	
    public Indemntekm(IndemntekmId id, int idDotation) {
        this.id = id;
        this.idDotation = idDotation;
    }
    public Indemntekm(IndemntekmId id, int idDotation, Integer montantDepInt, Integer kmRoute, Integer kmPiste, Integer mntKm) {
       this.id = id;
       this.idDotation = idDotation;
       this.montantDepInt = montantDepInt;
       this.kmRoute = kmRoute;
       this.kmPiste = kmPiste;
       this.mntKm = mntKm;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDeplacement", column=@Column(name="idDeplacement", nullable=false) ), 
        @AttributeOverride(name="idIndKm", column=@Column(name="idIndKm", nullable=false) ) } )
    public IndemntekmId getId() {
        return this.id;
    }
    
    public void setId(IndemntekmId id) {
        this.id = id;
    }

    
    @Column(name="idDotation", nullable=false)
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }

    
    @Column(name="montantDepInt", precision=8, scale=0)
    public Integer getMontantDepInt() {
        return this.montantDepInt;
    }
    
    public void setMontantDepInt(Integer montantDepInt) {
        this.montantDepInt = montantDepInt;
    }

    
    @Column(name="kmRoute", precision=8, scale=0)
    public Integer getKmRoute() {
        return this.kmRoute;
    }
    
    public void setKmRoute(Integer kmRoute) {
        this.kmRoute = kmRoute;
    }

    
    @Column(name="kmPiste", precision=8, scale=0)
    public Integer getKmPiste() {
        return this.kmPiste;
    }
    
    public void setKmPiste(Integer kmPiste) {
        this.kmPiste = kmPiste;
    }

    
    @Column(name="mntKm")
    public Integer getMntKm() {
        return this.mntKm;
    }
    
    public void setMntKm(Integer mntKm) {
        this.mntKm = mntKm;
    }




}


