package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Indemntekm generated by hbm2java
 */
public class Indemntekm  implements java.io.Serializable {


     private IndemntekmId id;
     private int idDotation;
     private Integer montantDepInt;
     private Integer kmRoute;
     private Integer kmPiste;
     private Integer mntKm;

    public Indemntekm() {
    }

	
    public Indemntekm(IndemntekmId id, int idDotation) {
        this.id = id;
        this.idDotation = idDotation;
    }
    public Indemntekm(IndemntekmId id, int idDotation, Integer montantDepInt, Integer kmRoute, Integer kmPiste, Integer mntKm) {
       this.id = id;
       this.idDotation = idDotation;
       this.montantDepInt = montantDepInt;
       this.kmRoute = kmRoute;
       this.kmPiste = kmPiste;
       this.mntKm = mntKm;
    }
   
    public IndemntekmId getId() {
        return this.id;
    }
    
    public void setId(IndemntekmId id) {
        this.id = id;
    }
    public int getIdDotation() {
        return this.idDotation;
    }
    
    public void setIdDotation(int idDotation) {
        this.idDotation = idDotation;
    }
    public Integer getMontantDepInt() {
        return this.montantDepInt;
    }
    
    public void setMontantDepInt(Integer montantDepInt) {
        this.montantDepInt = montantDepInt;
    }
    public Integer getKmRoute() {
        return this.kmRoute;
    }
    
    public void setKmRoute(Integer kmRoute) {
        this.kmRoute = kmRoute;
    }
    public Integer getKmPiste() {
        return this.kmPiste;
    }
    
    public void setKmPiste(Integer kmPiste) {
        this.kmPiste = kmPiste;
    }
    public Integer getMntKm() {
        return this.mntKm;
    }
    
    public void setMntKm(Integer mntKm) {
        this.mntKm = mntKm;
    }




}


