package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * IndemnetedeplacementinterneId generated by hbm2java
 */
public class IndemnetedeplacementinterneId  implements java.io.Serializable {


     private int idDeplacement;
     private int idIndDep;

    public IndemnetedeplacementinterneId() {
    }

    public IndemnetedeplacementinterneId(int idDeplacement, int idIndDep) {
       this.idDeplacement = idDeplacement;
       this.idIndDep = idIndDep;
    }
   
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public int getIdIndDep() {
        return this.idIndDep;
    }
    
    public void setIdIndDep(int idIndDep) {
        this.idIndDep = idIndDep;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndemnetedeplacementinterneId) ) return false;
		 IndemnetedeplacementinterneId castOther = ( IndemnetedeplacementinterneId ) other; 
         
		 return (this.getIdDeplacement()==castOther.getIdDeplacement())
 && (this.getIdIndDep()==castOther.getIdIndDep());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDeplacement();
         result = 37 * result + this.getIdIndDep();
         return result;
   }   


}


