package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndemntekmId generated by hbm2java
 */
@Embeddable
public class IndemntekmId  implements java.io.Serializable {


     private int idDeplacement;
     private int idIndKm;

    public IndemntekmId() {
    }

    public IndemntekmId(int idDeplacement, int idIndKm) {
       this.idDeplacement = idDeplacement;
       this.idIndKm = idIndKm;
    }
   


    @Column(name="idDeplacement", nullable=false)
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }


    @Column(name="idIndKm", nullable=false)
    public int getIdIndKm() {
        return this.idIndKm;
    }
    
    public void setIdIndKm(int idIndKm) {
        this.idIndKm = idIndKm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndemntekmId) ) return false;
		 IndemntekmId castOther = ( IndemntekmId ) other; 
         
		 return (this.getIdDeplacement()==castOther.getIdDeplacement())
 && (this.getIdIndKm()==castOther.getIdIndKm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDeplacement();
         result = 37 * result + this.getIdIndKm();
         return result;
   }   


}


