package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Intervenant generated by hbm2java
 */
public class Intervenant  implements java.io.Serializable {


     private String cinPpr;
     private int idUser;
     private String nomComplet;
     private String nomArabe;
     private String telephone;
     private String mail;

    public Intervenant() {
    }

	
    public Intervenant(String cinPpr, int idUser) {
        this.cinPpr = cinPpr;
        this.idUser = idUser;
    }
    public Intervenant(String cinPpr, int idUser, String nomComplet, String nomArabe, String telephone, String mail) {
       this.cinPpr = cinPpr;
       this.idUser = idUser;
       this.nomComplet = nomComplet;
       this.nomArabe = nomArabe;
       this.telephone = telephone;
       this.mail = mail;
    }
   
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }
    public String getNomArabe() {
        return this.nomArabe;
    }
    
    public void setNomArabe(String nomArabe) {
        this.nomArabe = nomArabe;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


