package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Intervenant generated by hbm2java
 */
@Entity
@Table(name="intervenant"
    ,catalog="finance_fssm"
)
public class Intervenant  implements java.io.Serializable {


     private String cinPpr;
     private int idUser;
     private String nomComplet;
     private String nomArabe;
     private String telephone;
     private String mail;

    public Intervenant() {
    }

	
    public Intervenant(String cinPpr, int idUser) {
        this.cinPpr = cinPpr;
        this.idUser = idUser;
    }
    public Intervenant(String cinPpr, int idUser, String nomComplet, String nomArabe, String telephone, String mail) {
       this.cinPpr = cinPpr;
       this.idUser = idUser;
       this.nomComplet = nomComplet;
       this.nomArabe = nomArabe;
       this.telephone = telephone;
       this.mail = mail;
    }
   
     @Id 

    
    @Column(name="cinPpr", unique=true, nullable=false, length=254)
    public String getCinPpr() {
        return this.cinPpr;
    }
    
    public void setCinPpr(String cinPpr) {
        this.cinPpr = cinPpr;
    }

    
    @Column(name="idUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="nomComplet", length=254)
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }

    
    @Column(name="nomArabe", length=254)
    public String getNomArabe() {
        return this.nomArabe;
    }
    
    public void setNomArabe(String nomArabe) {
        this.nomArabe = nomArabe;
    }

    
    @Column(name="telephone", length=254)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="mail", length=254)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


