package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lignecommande generated by hbm2java
 */
@Entity
@Table(name="lignecommande"
    ,catalog="bd_finance_fssm"
)
public class Lignecommande  implements java.io.Serializable {


     private Integer idLigne;
     private int idBc;
     private int idArticle;
     private Integer quantite;
     private Integer pu;
     private Integer montant;

    public Lignecommande() {
    }

	
    public Lignecommande(int idBc, int idArticle) {
        this.idBc = idBc;
        this.idArticle = idArticle;
    }
    public Lignecommande(int idBc, int idArticle, Integer quantite, Integer pu, Integer montant) {
       this.idBc = idBc;
       this.idArticle = idArticle;
       this.quantite = quantite;
       this.pu = pu;
       this.montant = montant;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idLigne", unique=true, nullable=false)
    public Integer getIdLigne() {
        return this.idLigne;
    }
    
    public void setIdLigne(Integer idLigne) {
        this.idLigne = idLigne;
    }

    
    @Column(name="idBC", nullable=false)
    public int getIdBc() {
        return this.idBc;
    }
    
    public void setIdBc(int idBc) {
        this.idBc = idBc;
    }

    
    @Column(name="idArticle", nullable=false)
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }

    
    @Column(name="quantite")
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="pu", precision=8, scale=0)
    public Integer getPu() {
        return this.pu;
    }
    
    public void setPu(Integer pu) {
        this.pu = pu;
    }

    
    @Column(name="montant", precision=8, scale=0)
    public Integer getMontant() {
        return this.montant;
    }
    
    public void setMontant(Integer montant) {
        this.montant = montant;
    }




}


