package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Lignecommande generated by hbm2java
 */
public class Lignecommande  implements java.io.Serializable {


     private Integer idLigne;
     private int idBc;
     private int idArticle;
     private Integer quantite;
     private Integer pu;
     private Integer montant;

    public Lignecommande() {
    }

	
    public Lignecommande(int idBc, int idArticle) {
        this.idBc = idBc;
        this.idArticle = idArticle;
    }
    public Lignecommande(int idBc, int idArticle, Integer quantite, Integer pu, Integer montant) {
       this.idBc = idBc;
       this.idArticle = idArticle;
       this.quantite = quantite;
       this.pu = pu;
       this.montant = montant;
    }
   
    public Integer getIdLigne() {
        return this.idLigne;
    }
    
    public void setIdLigne(Integer idLigne) {
        this.idLigne = idLigne;
    }
    public int getIdBc() {
        return this.idBc;
    }
    
    public void setIdBc(int idBc) {
        this.idBc = idBc;
    }
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }
    public Integer getPu() {
        return this.pu;
    }
    
    public void setPu(Integer pu) {
        this.pu = pu;
    }
    public Integer getMontant() {
        return this.montant;
    }
    
    public void setMontant(Integer montant) {
        this.montant = montant;
    }




}


