package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name="pays"
    ,catalog="bd_finance_fssm"
)
public class Pays  implements java.io.Serializable {


     private Integer idPays;
     private String ville;
     private String nomPays;

    public Pays() {
    }

    public Pays(String ville, String nomPays) {
       this.ville = ville;
       this.nomPays = nomPays;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPays", unique=true, nullable=false)
    public Integer getIdPays() {
        return this.idPays;
    }
    
    public void setIdPays(Integer idPays) {
        this.idPays = idPays;
    }

    
    @Column(name="ville", length=254)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="nomPays", length=254)
    public String getNomPays() {
        return this.nomPays;
    }
    
    public void setNomPays(String nomPays) {
        this.nomPays = nomPays;
    }




}


