package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private Integer idPays;
     private String ville;
     private String nomPays;

    public Pays() {
    }

    public Pays(String ville, String nomPays) {
       this.ville = ville;
       this.nomPays = nomPays;
    }
   
    public Integer getIdPays() {
        return this.idPays;
    }
    
    public void setIdPays(Integer idPays) {
        this.idPays = idPays;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getNomPays() {
        return this.nomPays;
    }
    
    public void setNomPays(String nomPays) {
        this.nomPays = nomPays;
    }




}


