package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Piecejustificativedeplacement generated by hbm2java
 */
public class Piecejustificativedeplacement  implements java.io.Serializable {


     private Integer idPiece;
     private int idDeplacement;
     private Date datePiece;
     private String intutilePiece;
     private String piece;

    public Piecejustificativedeplacement() {
    }

	
    public Piecejustificativedeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public Piecejustificativedeplacement(int idDeplacement, Date datePiece, String intutilePiece, String piece) {
       this.idDeplacement = idDeplacement;
       this.datePiece = datePiece;
       this.intutilePiece = intutilePiece;
       this.piece = piece;
    }
   
    public Integer getIdPiece() {
        return this.idPiece;
    }
    
    public void setIdPiece(Integer idPiece) {
        this.idPiece = idPiece;
    }
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public Date getDatePiece() {
        return this.datePiece;
    }
    
    public void setDatePiece(Date datePiece) {
        this.datePiece = datePiece;
    }
    public String getIntutilePiece() {
        return this.intutilePiece;
    }
    
    public void setIntutilePiece(String intutilePiece) {
        this.intutilePiece = intutilePiece;
    }
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }




}


