package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Piecejustificativevacation generated by hbm2java
 */
public class Piecejustificativevacation  implements java.io.Serializable {


     private Integer idPiece;
     private int idDossier;
     private int dosIdDossier;
     private Date datePiece;
     private String intutilePiece;
     private String piece;

    public Piecejustificativevacation() {
    }

	
    public Piecejustificativevacation(int idDossier, int dosIdDossier) {
        this.idDossier = idDossier;
        this.dosIdDossier = dosIdDossier;
    }
    public Piecejustificativevacation(int idDossier, int dosIdDossier, Date datePiece, String intutilePiece, String piece) {
       this.idDossier = idDossier;
       this.dosIdDossier = dosIdDossier;
       this.datePiece = datePiece;
       this.intutilePiece = intutilePiece;
       this.piece = piece;
    }
   
    public Integer getIdPiece() {
        return this.idPiece;
    }
    
    public void setIdPiece(Integer idPiece) {
        this.idPiece = idPiece;
    }
    public int getIdDossier() {
        return this.idDossier;
    }
    
    public void setIdDossier(int idDossier) {
        this.idDossier = idDossier;
    }
    public int getDosIdDossier() {
        return this.dosIdDossier;
    }
    
    public void setDosIdDossier(int dosIdDossier) {
        this.dosIdDossier = dosIdDossier;
    }
    public Date getDatePiece() {
        return this.datePiece;
    }
    
    public void setDatePiece(Date datePiece) {
        this.datePiece = datePiece;
    }
    public String getIntutilePiece() {
        return this.intutilePiece;
    }
    
    public void setIntutilePiece(String intutilePiece) {
        this.intutilePiece = intutilePiece;
    }
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }




}


