package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Piecejustificativevacation generated by hbm2java
 */
@Entity
@Table(name="piecejustificativevacation"
    ,catalog="finance_fssm"
)
public class Piecejustificativevacation  implements java.io.Serializable {


     private Integer idPiece;
     private int idDossier;
     private int dosIdDossier;
     private Date datePiece;
     private String intutilePiece;
     private String piece;

    public Piecejustificativevacation() {
    }

	
    public Piecejustificativevacation(int idDossier, int dosIdDossier) {
        this.idDossier = idDossier;
        this.dosIdDossier = dosIdDossier;
    }
    public Piecejustificativevacation(int idDossier, int dosIdDossier, Date datePiece, String intutilePiece, String piece) {
       this.idDossier = idDossier;
       this.dosIdDossier = dosIdDossier;
       this.datePiece = datePiece;
       this.intutilePiece = intutilePiece;
       this.piece = piece;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPiece", unique=true, nullable=false)
    public Integer getIdPiece() {
        return this.idPiece;
    }
    
    public void setIdPiece(Integer idPiece) {
        this.idPiece = idPiece;
    }

    
    @Column(name="idDossier", nullable=false)
    public int getIdDossier() {
        return this.idDossier;
    }
    
    public void setIdDossier(int idDossier) {
        this.idDossier = idDossier;
    }

    
    @Column(name="Dos_idDossier", nullable=false)
    public int getDosIdDossier() {
        return this.dosIdDossier;
    }
    
    public void setDosIdDossier(int dosIdDossier) {
        this.dosIdDossier = dosIdDossier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datePiece", length=19)
    public Date getDatePiece() {
        return this.datePiece;
    }
    
    public void setDatePiece(Date datePiece) {
        this.datePiece = datePiece;
    }

    
    @Column(name="intutilePiece", length=254)
    public String getIntutilePiece() {
        return this.intutilePiece;
    }
    
    public void setIntutilePiece(String intutilePiece) {
        this.intutilePiece = intutilePiece;
    }

    
    @Column(name="piece", length=254)
    public String getPiece() {
        return this.piece;
    }
    
    public void setPiece(String piece) {
        this.piece = piece;
    }




}


