package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Prixkilomitrique generated by hbm2java
 */
public class Prixkilomitrique  implements java.io.Serializable {


     private Integer idPrixKilo;
     private Integer kmSup;
     private Integer kmInf;
     private Integer prixRoute;
     private Integer prixPiste;

    public Prixkilomitrique() {
    }

    public Prixkilomitrique(Integer kmSup, Integer kmInf, Integer prixRoute, Integer prixPiste) {
       this.kmSup = kmSup;
       this.kmInf = kmInf;
       this.prixRoute = prixRoute;
       this.prixPiste = prixPiste;
    }
   
    public Integer getIdPrixKilo() {
        return this.idPrixKilo;
    }
    
    public void setIdPrixKilo(Integer idPrixKilo) {
        this.idPrixKilo = idPrixKilo;
    }
    public Integer getKmSup() {
        return this.kmSup;
    }
    
    public void setKmSup(Integer kmSup) {
        this.kmSup = kmSup;
    }
    public Integer getKmInf() {
        return this.kmInf;
    }
    
    public void setKmInf(Integer kmInf) {
        this.kmInf = kmInf;
    }
    public Integer getPrixRoute() {
        return this.prixRoute;
    }
    
    public void setPrixRoute(Integer prixRoute) {
        this.prixRoute = prixRoute;
    }
    public Integer getPrixPiste() {
        return this.prixPiste;
    }
    
    public void setPrixPiste(Integer prixPiste) {
        this.prixPiste = prixPiste;
    }




}


