package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Prixrepas generated by hbm2java
 */
public class Prixrepas  implements java.io.Serializable {


     private Integer idPrixRepas;
     private Integer indiceSup;
     private Integer indiceInf;
     private Integer prixDs;
     private Integer prixD;
     private Integer prixRs;

    public Prixrepas() {
    }

    public Prixrepas(Integer indiceSup, Integer indiceInf, Integer prixDs, Integer prixD, Integer prixRs) {
       this.indiceSup = indiceSup;
       this.indiceInf = indiceInf;
       this.prixDs = prixDs;
       this.prixD = prixD;
       this.prixRs = prixRs;
    }
   
    public Integer getIdPrixRepas() {
        return this.idPrixRepas;
    }
    
    public void setIdPrixRepas(Integer idPrixRepas) {
        this.idPrixRepas = idPrixRepas;
    }
    public Integer getIndiceSup() {
        return this.indiceSup;
    }
    
    public void setIndiceSup(Integer indiceSup) {
        this.indiceSup = indiceSup;
    }
    public Integer getIndiceInf() {
        return this.indiceInf;
    }
    
    public void setIndiceInf(Integer indiceInf) {
        this.indiceInf = indiceInf;
    }
    public Integer getPrixDs() {
        return this.prixDs;
    }
    
    public void setPrixDs(Integer prixDs) {
        this.prixDs = prixDs;
    }
    public Integer getPrixD() {
        return this.prixD;
    }
    
    public void setPrixD(Integer prixD) {
        this.prixD = prixD;
    }
    public Integer getPrixRs() {
        return this.prixRs;
    }
    
    public void setPrixRs(Integer prixRs) {
        this.prixRs = prixRs;
    }




}


