package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Prixsejour generated by hbm2java
 */
public class Prixsejour  implements java.io.Serializable {


     private Integer idPrixSej;
     private Integer grade;
     private Integer prix;

    public Prixsejour() {
    }

    public Prixsejour(Integer grade, Integer prix) {
       this.grade = grade;
       this.prix = prix;
    }
   
    public Integer getIdPrixSej() {
        return this.idPrixSej;
    }
    
    public void setIdPrixSej(Integer idPrixSej) {
        this.idPrixSej = idPrixSej;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
    public Integer getPrix() {
        return this.prix;
    }
    
    public void setPrix(Integer prix) {
        this.prix = prix;
    }




}


