package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prixrepas generated by hbm2java
 */
@Entity
@Table(name="prixrepas"
    ,catalog="bd_finance_fssm"
)
public class Prixrepas  implements java.io.Serializable {


     private Integer idPrixRepas;
     private Integer indiceSup;
     private Integer indiceInf;
     private Integer prixDs;
     private Integer prixD;
     private Integer prixRs;

    public Prixrepas() {
    }

    public Prixrepas(Integer indiceSup, Integer indiceInf, Integer prixDs, Integer prixD, Integer prixRs) {
       this.indiceSup = indiceSup;
       this.indiceInf = indiceInf;
       this.prixDs = prixDs;
       this.prixD = prixD;
       this.prixRs = prixRs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPrixRepas", unique=true, nullable=false)
    public Integer getIdPrixRepas() {
        return this.idPrixRepas;
    }
    
    public void setIdPrixRepas(Integer idPrixRepas) {
        this.idPrixRepas = idPrixRepas;
    }

    
    @Column(name="indiceSup")
    public Integer getIndiceSup() {
        return this.indiceSup;
    }
    
    public void setIndiceSup(Integer indiceSup) {
        this.indiceSup = indiceSup;
    }

    
    @Column(name="indiceInf")
    public Integer getIndiceInf() {
        return this.indiceInf;
    }
    
    public void setIndiceInf(Integer indiceInf) {
        this.indiceInf = indiceInf;
    }

    
    @Column(name="prixDs", precision=8, scale=0)
    public Integer getPrixDs() {
        return this.prixDs;
    }
    
    public void setPrixDs(Integer prixDs) {
        this.prixDs = prixDs;
    }

    
    @Column(name="prixD", precision=8, scale=0)
    public Integer getPrixD() {
        return this.prixD;
    }
    
    public void setPrixD(Integer prixD) {
        this.prixD = prixD;
    }

    
    @Column(name="prixRs", precision=8, scale=0)
    public Integer getPrixRs() {
        return this.prixRs;
    }
    
    public void setPrixRs(Integer prixRs) {
        this.prixRs = prixRs;
    }




}


