package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prixkilomitrique generated by hbm2java
 */
@Entity
@Table(name="prixkilomitrique"
    ,catalog="finance_fssm"
)
public class Prixkilomitrique  implements java.io.Serializable {


     private Integer idPrixKilo;
     private Integer kmSup;
     private Integer kmInf;
     private Integer prixRoute;
     private Integer prixPiste;

    public Prixkilomitrique() {
    }

    public Prixkilomitrique(Integer kmSup, Integer kmInf, Integer prixRoute, Integer prixPiste) {
       this.kmSup = kmSup;
       this.kmInf = kmInf;
       this.prixRoute = prixRoute;
       this.prixPiste = prixPiste;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPrixKilo", unique=true, nullable=false)
    public Integer getIdPrixKilo() {
        return this.idPrixKilo;
    }
    
    public void setIdPrixKilo(Integer idPrixKilo) {
        this.idPrixKilo = idPrixKilo;
    }

    
    @Column(name="kmSup", precision=8, scale=0)
    public Integer getKmSup() {
        return this.kmSup;
    }
    
    public void setKmSup(Integer kmSup) {
        this.kmSup = kmSup;
    }

    
    @Column(name="kmInf", precision=8, scale=0)
    public Integer getKmInf() {
        return this.kmInf;
    }
    
    public void setKmInf(Integer kmInf) {
        this.kmInf = kmInf;
    }

    
    @Column(name="prixRoute", precision=8, scale=0)
    public Integer getPrixRoute() {
        return this.prixRoute;
    }
    
    public void setPrixRoute(Integer prixRoute) {
        this.prixRoute = prixRoute;
    }

    
    @Column(name="prixPiste", precision=8, scale=0)
    public Integer getPrixPiste() {
        return this.prixPiste;
    }
    
    public void setPrixPiste(Integer prixPiste) {
        this.prixPiste = prixPiste;
    }




}


