package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Releve generated by hbm2java
 */
@Entity
@Table(name="releve"
    ,catalog="finance_fssm"
)
public class Releve  implements java.io.Serializable {


     private Integer idRelever;
     private int idFiliere;
     private String semestre;
     private String anneeUniversitaire;

    public Releve() {
    }

	
    public Releve(int idFiliere) {
        this.idFiliere = idFiliere;
    }
    public Releve(int idFiliere, String semestre, String anneeUniversitaire) {
       this.idFiliere = idFiliere;
       this.semestre = semestre;
       this.anneeUniversitaire = anneeUniversitaire;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRelever", unique=true, nullable=false)
    public Integer getIdRelever() {
        return this.idRelever;
    }
    
    public void setIdRelever(Integer idRelever) {
        this.idRelever = idRelever;
    }

    
    @Column(name="idFiliere", nullable=false)
    public int getIdFiliere() {
        return this.idFiliere;
    }
    
    public void setIdFiliere(int idFiliere) {
        this.idFiliere = idFiliere;
    }

    
    @Column(name="semestre", length=254)
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }

    
    @Column(name="anneeUniversitaire", length=254)
    public String getAnneeUniversitaire() {
        return this.anneeUniversitaire;
    }
    
    public void setAnneeUniversitaire(String anneeUniversitaire) {
        this.anneeUniversitaire = anneeUniversitaire;
    }




}


