package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Releve generated by hbm2java
 */
public class Releve  implements java.io.Serializable {


     private Integer idRelever;
     private int idFiliere;
     private String semestre;
     private String anneeUniversitaire;

    public Releve() {
    }

	
    public Releve(int idFiliere) {
        this.idFiliere = idFiliere;
    }
    public Releve(int idFiliere, String semestre, String anneeUniversitaire) {
       this.idFiliere = idFiliere;
       this.semestre = semestre;
       this.anneeUniversitaire = anneeUniversitaire;
    }
   
    public Integer getIdRelever() {
        return this.idRelever;
    }
    
    public void setIdRelever(Integer idRelever) {
        this.idRelever = idRelever;
    }
    public int getIdFiliere() {
        return this.idFiliere;
    }
    
    public void setIdFiliere(int idFiliere) {
        this.idFiliere = idFiliere;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getAnneeUniversitaire() {
        return this.anneeUniversitaire;
    }
    
    public void setAnneeUniversitaire(String anneeUniversitaire) {
        this.anneeUniversitaire = anneeUniversitaire;
    }




}


