package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,catalog="bd_finance_fssm"
)
public class Role  implements java.io.Serializable {


     private Integer idRole;
     private String nom;

    public Role() {
    }

    public Role(String nom) {
       this.nom = nom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRole", unique=true, nullable=false)
    public Integer getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    
    @Column(name="nom", length=254)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


