package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Secteurprincipal generated by hbm2java
 */
public class Secteurprincipal  implements java.io.Serializable {


     private Integer idSecteurP;
     private String designation;

    public Secteurprincipal() {
    }

    public Secteurprincipal(String designation) {
       this.designation = designation;
    }
   
    public Integer getIdSecteurP() {
        return this.idSecteurP;
    }
    
    public void setIdSecteurP(Integer idSecteurP) {
        this.idSecteurP = idSecteurP;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


