package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Secteur generated by hbm2java
 */
@Entity
@Table(name="secteur"
    ,catalog="bd_finance_fssm"
)
public class Secteur  implements java.io.Serializable {


     private Integer idSecteur;
     private Integer idSecteurP;
     private String intituleSecteur;

    public Secteur() {
    }

    public Secteur(Integer idSecteurP, String intituleSecteur) {
       this.idSecteurP = idSecteurP;
       this.intituleSecteur = intituleSecteur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSecteur", unique=true, nullable=false)
    public Integer getIdSecteur() {
        return this.idSecteur;
    }
    
    public void setIdSecteur(Integer idSecteur) {
        this.idSecteur = idSecteur;
    }

    
    @Column(name="idSecteurP")
    public Integer getIdSecteurP() {
        return this.idSecteurP;
    }
    
    public void setIdSecteurP(Integer idSecteurP) {
        this.idSecteurP = idSecteurP;
    }

    
    @Column(name="intituleSecteur", length=254)
    public String getIntituleSecteur() {
        return this.intituleSecteur;
    }
    
    public void setIntituleSecteur(String intituleSecteur) {
        this.intituleSecteur = intituleSecteur;
    }




}


