package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Secteur generated by hbm2java
 */
public class Secteur  implements java.io.Serializable {


     private Integer idSecteur;
     private Integer idSecteurP;
     private String intituleSecteur;

    public Secteur() {
    }

    public Secteur(Integer idSecteurP, String intituleSecteur) {
       this.idSecteurP = idSecteurP;
       this.intituleSecteur = intituleSecteur;
    }
   
    public Integer getIdSecteur() {
        return this.idSecteur;
    }
    
    public void setIdSecteur(Integer idSecteur) {
        this.idSecteur = idSecteur;
    }
    public Integer getIdSecteurP() {
        return this.idSecteurP;
    }
    
    public void setIdSecteurP(Integer idSecteurP) {
        this.idSecteurP = idSecteurP;
    }
    public String getIntituleSecteur() {
        return this.intituleSecteur;
    }
    
    public void setIntituleSecteur(String intituleSecteur) {
        this.intituleSecteur = intituleSecteur;
    }




}


