package models;
// Generated 4 juin 2016 18:10:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeformations generated by hbm2java
 */
@Entity
@Table(name="typeformations"
    ,catalog="finance_fssm"
)
public class Typeformations  implements java.io.Serializable {


     private Integer idType;
     private String nomType;

    public Typeformations() {
    }

    public Typeformations(String nomType) {
       this.nomType = nomType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idType", unique=true, nullable=false)
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    
    @Column(name="nomType", length=254)
    public String getNomType() {
        return this.nomType;
    }
    
    public void setNomType(String nomType) {
        this.nomType = nomType;
    }




}


