package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Typeformations generated by hbm2java
 */
public class Typeformations  implements java.io.Serializable {


     private Integer idType;
     private String nomType;

    public Typeformations() {
    }

    public Typeformations(String nomType) {
       this.nomType = nomType;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getNomType() {
        return this.nomType;
    }
    
    public void setNomType(String nomType) {
        this.nomType = nomType;
    }




}


