package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer idUserRole;
     private int idUser;
     private int idRole;

    public UserRole() {
    }

    public UserRole(int idUser, int idRole) {
       this.idUser = idUser;
       this.idRole = idRole;
    }
   
    public Integer getIdUserRole() {
        return this.idUserRole;
    }
    
    public void setIdUserRole(Integer idUserRole) {
        this.idUserRole = idUserRole;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }




}


