package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="user_role"
    ,catalog="bd_finance_fssm"
)
public class UserRole  implements java.io.Serializable {


     private Integer idUserRole;
     private int idUser;
     private int idRole;

    public UserRole() {
    }

    public UserRole(int idUser, int idRole) {
       this.idUser = idUser;
       this.idRole = idRole;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUserRole", unique=true, nullable=false)
    public Integer getIdUserRole() {
        return this.idUserRole;
    }
    
    public void setIdUserRole(Integer idUserRole) {
        this.idUserRole = idUserRole;
    }

    
    @Column(name="idUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="idRole", nullable=false)
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }




}


