package models;
// Generated 4 juin 2016 20:47:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Voiture generated by hbm2java
 */
@Entity
@Table(name="voiture"
    ,catalog="bd_finance_fssm"
)
public class Voiture  implements java.io.Serializable {


     private Integer idVoiture;
     private int idPrixKilo;
     private int idDeplacement;
     private int idIndKm;
     private String marque;
     private Integer puissance;

    public Voiture() {
    }

	
    public Voiture(int idPrixKilo, int idDeplacement, int idIndKm) {
        this.idPrixKilo = idPrixKilo;
        this.idDeplacement = idDeplacement;
        this.idIndKm = idIndKm;
    }
    public Voiture(int idPrixKilo, int idDeplacement, int idIndKm, String marque, Integer puissance) {
       this.idPrixKilo = idPrixKilo;
       this.idDeplacement = idDeplacement;
       this.idIndKm = idIndKm;
       this.marque = marque;
       this.puissance = puissance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVoiture", unique=true, nullable=false)
    public Integer getIdVoiture() {
        return this.idVoiture;
    }
    
    public void setIdVoiture(Integer idVoiture) {
        this.idVoiture = idVoiture;
    }

    
    @Column(name="idPrixKilo", nullable=false)
    public int getIdPrixKilo() {
        return this.idPrixKilo;
    }
    
    public void setIdPrixKilo(int idPrixKilo) {
        this.idPrixKilo = idPrixKilo;
    }

    
    @Column(name="idDeplacement", nullable=false)
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }

    
    @Column(name="idIndKm", nullable=false)
    public int getIdIndKm() {
        return this.idIndKm;
    }
    
    public void setIdIndKm(int idIndKm) {
        this.idIndKm = idIndKm;
    }

    
    @Column(name="marque", length=254)
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }

    
    @Column(name="puissance")
    public Integer getPuissance() {
        return this.puissance;
    }
    
    public void setPuissance(Integer puissance) {
        this.puissance = puissance;
    }




}


