package models;
// Generated 4 juin 2016 14:39:34 by Hibernate Tools 4.3.1



/**
 * Voiture generated by hbm2java
 */
public class Voiture  implements java.io.Serializable {


     private Integer idVoiture;
     private int idPrixKilo;
     private int idDeplacement;
     private int idIndKm;
     private String marque;
     private Integer puissance;

    public Voiture() {
    }

	
    public Voiture(int idPrixKilo, int idDeplacement, int idIndKm) {
        this.idPrixKilo = idPrixKilo;
        this.idDeplacement = idDeplacement;
        this.idIndKm = idIndKm;
    }
    public Voiture(int idPrixKilo, int idDeplacement, int idIndKm, String marque, Integer puissance) {
       this.idPrixKilo = idPrixKilo;
       this.idDeplacement = idDeplacement;
       this.idIndKm = idIndKm;
       this.marque = marque;
       this.puissance = puissance;
    }
   
    public Integer getIdVoiture() {
        return this.idVoiture;
    }
    
    public void setIdVoiture(Integer idVoiture) {
        this.idVoiture = idVoiture;
    }
    public int getIdPrixKilo() {
        return this.idPrixKilo;
    }
    
    public void setIdPrixKilo(int idPrixKilo) {
        this.idPrixKilo = idPrixKilo;
    }
    public int getIdDeplacement() {
        return this.idDeplacement;
    }
    
    public void setIdDeplacement(int idDeplacement) {
        this.idDeplacement = idDeplacement;
    }
    public int getIdIndKm() {
        return this.idIndKm;
    }
    
    public void setIdIndKm(int idIndKm) {
        this.idIndKm = idIndKm;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public Integer getPuissance() {
        return this.puissance;
    }
    
    public void setPuissance(Integer puissance) {
        this.puissance = puissance;
    }




}


